version: "3.8"

services:
  postgres_db:
    platform: linux/amd64
    image: postgres:latest
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DATABASE
    ports:
      - $POSTGRES_LOCAL_PORT:$POSTGRES_DOCKER_PORT
  app:
    depends_on:
      - postgres_db
    restart: on-failure
    image: auto_service_app
    build: .
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
      - $DEBUG_PORT:$DEBUG_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
              "spring.datasource.url"  : "jdbc:postgresql://postgres_db:$POSTGRES_DOCKER_PORT/$POSTGRES_DATABASE?serverTimezone=UTC",
              "spring.datasource.username" : "$POSTGRES_USER",
              "spring.datasource.password" : "$POSTGRES_PASSWORD",
              "spring.liquibase.url" : "jdbc:postgresql://postgres_db:$POSTGRES_DOCKER_PORT/$POSTGRES_DATABASE?serverTimezone=UTC",
              "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
              "spring.jpa.hibernate.ddl-auto" : "validate",
              "spring.liquibase.user" : "$POSTGRES_USER",
              "spring.liquibase.password" : "$POSTGRES_PASSWORD"
            }'
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
